import type { Metadata } from "next";
import { Geist, Geist_Mono, Outfit } from "next/font/google";
import { MainProvider } from "./providers";
import { getLocale, getMessages } from "next-intl/server";
import { cookies } from "next/headers";

import "./globals.css";
import { getUser } from "@/entities/user";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const user = await getUser();
  const messages = await getMessages();
  const themeCookie = (await cookies()).get("theme")?.value ?? "system";
  return (
    <html className={themeCookie} lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} antialiased`}
      >
        <MainProvider initialUser={user} locale={locale} messages={messages}>
          {children}
        </MainProvider>
      </body>
    </html>
  );
}
